List assets in goal account balance
algorand/go-algorand pull request #1583
Opened 2020-10-02 14:03 UTC by jasonpaulos

## Summary

Report ASA balances in `goal account balance`.

For example, viewing the balance of the BetaNet account 5K6OH2HKK3HORMIAQT7JYCUUYJTWS5KQ4AL7ITPI2SOCBKA7LMEEJYT5LA produces:

```
$ goal account balance -a 5K6OH2HKK3HORMIAQT7JYCUUYJTWS5KQ4AL7ITPI2SOCBKA7LMEEJYT5LA -d data
99995000 microAlgos
1000 AC, A-Coin, ID 2678221
1000 BC, <unnamed asset>, ID 2678222
1000 units, C-Coin, ID 2678223
10.00 DC, D-Coin, ID 2678224 (frozen)
```

The format for assets is `{amount} {unit name}, {asset name}, ID {asset ID} {frozen?}`. If the asset does not have a unit name, "units" is used, and if the asset does not have a name, "\<unnamed asset\>" is used. The assets are ordered by ID.

When viewing the balance of an account that does not have any assets, only the microAlgos are displayed, as usual.

Closes #1487.

## Test Plan

I have added a goal expect test to verify the command output is correct. The test checks the output of an account with no assets and with similar assets to the above example.

2020-10-02 14:56 UTC, EvanJRichard approved these changes
Looking good to me, :ship: pending tests passing!

2020-10-02 16:07 UTC, tsachiherman commented
Could you please confirm that with @rotemh ? I'm a bit habitant about this one since it was kicked off by a third-party request and did no come as internal design. Specifically, it breaks the existing goal interface, and seems to be missing the applications.

When I originally read that ticket, I was thinking of changing the `Long` string so it would align with the current implementation.

2020-10-04 08:14 UTC, algorotem commented
@tsachiherman are we worried about someone who uses goal's output as an input to another program? If this is the case, In my view, it's ok to change it because goal was never defined (nor designed) to be a dev tool in that sense.

With that, I do think that we need to keep the "feel" consistent across commands and this one should be closer to `account list`. 

Per the Applications, this is the `balance` command and feels "incorrect" to me to have the applications their as well. Maybe the better solution is to deprecate this one and create a new `goal account info` that returns all balances and applications?

2020-10-05 13:04 UTC, tsachiherman commented
Yes, your plan sounds much better:
1. remove asset information from `goal account list`
2. keep `goal account balance` as is, updating the `Long` to indicate that it won't be providing the asset information
3. adding `goal account info` which would be able to provide assets and app information for any specified account.

one thing to note is that it would be nice if we can use the output of #1 as the input to #3. Alternatively, add a flag to #1 so that it would add the account information.

2020-10-19 15:40 UTC, jasonpaulos commented
@tsachiherman I've updated this PR with the above changes. Let me know if it looks good to you.

2020-10-19 15:58 UTC, tsachiherman requested changes
@jasonpaulos, great work implementing these, I have few more (smaller) requests related to the code changes - 
Calling `reportErrorf` in `printAccountInfo` is correct, but would result in weird output, as only some of the account information would be presented.
( i.e. calling `reportErrorf` would terminate the process )
I have few suggestions that could improve this use case:
1. Accumulate the output string, and output it with a single `reportInfof` ( which also better align with separating the formatting and outputting )
2. Promote the error case to the top, so you could identify the error case first
3. The error output of "Error processing command: %s" is a pretty generic; I think that we can do better in this case. ( i.e. "Unable to retrieve asset information for asset %d referred by account %s : %v" )

2020-10-20 14:59 UTC, jasonpaulos commented
@tsachiherman nice catch, I forgot to remove that `reportErrorf`. I made changes to buffer the response and print any errors first. However, I chose not to use `reportInfof` for the time being because `unicodePrintable` thinks tabs (`\t`) are non-printable characters.

Let me know if you think this is acceptable for now, I should switch to using spaces for the indent, or I should modify `unicodePrintable` to allow tabs.

2020-10-20 15:20 UTC, tsachiherman commented
> @tsachiherman nice catch, I forgot to remove that `reportErrorf`. I made changes to buffer the response and print any errors first. However, I chose not to use `reportInfof` for the time being because `unicodePrintable` thinks tabs (`\t`) are non-printable characters.
> 
> Let me know if you think this is acceptable for now, I should switch to using spaces for the indent, or I should modify `unicodePrintable` to allow tabs.

I think that it's better, but we definitely need to have the errors sent to the stderr, plus exiting with a non-zero error code.
( i.e. that's why I suggested using the reportXXX functions )

2020-10-20 15:46 UTC, tsachiherman approved these changes
looks good; it's more common in go to return an error object compared to returning a success flag, but the code looks like it would work just fine.

2020-10-20 17:32 UTC, merged