Refactor parseIntcblock
algorand/go-algorand pull request #1644
Opened 2020-10-22 22:01 UTC by nicholasguoalgorand

## Summary

Modify the error messages for parseIntcblock to distinguish fro, parseBytecblock

## Test Plan

None

2020-10-22 22:51 UTC, tsachiherman commented
You'll need to add a unit test that confirm the correctness of the modified functions, but beside an extra space after `errShortIntcblock  =`, the change looks good.

2020-10-23 15:26 UTC, brianolson commented on data/transactions/logic/assembler.go
> +var errShortIntcblock  = errors.New("intcblock ran past end of program")
run `go fmt` or `make sanity`

2020-10-26 20:54 UTC, tsachiherman requested changes
Two small issues, looks good otherwise:
- Remove node.go and network.go from this PR. You haven't changes these, and it shouldn't be in this PR.
- The unit test for parseIntcblock is good, but we also need one for checkIntConstBlock. You can populate the content of the evalContext object you pass to checkIntConstBlock for test purposes.

2020-10-26 23:03 UTC, tsachiherman approved these changes

2020-10-27 12:36 UTC, merged