drop support for old-style Merkle txn root commitment
algorand/go-algorand pull request #1883
Opened 2021-02-01 16:12 UTC by zeldovich

This PR removes support for the Merkle transaction commitments that we used a long time ago (well before mainnet launch).  This will also help add support for a new form of Merkle tree commitment for transactions (PR #1879).

2021-02-01 16:55 UTC, tsachiherman requested changes
One small file that you've missed:
`./test/testdata/consensus/catchpointtestingprotocol.json`

2021-02-01 18:41 UTC, zeldovich commented
> One small file that you've missed:
> `./test/testdata/consensus/catchpointtestingprotocol.json`

Thanks for catching that!  I was indeed hoping to smoke out potential issues by seeing what Travis finds.

2021-02-01 19:04 UTC, tsachiherman commented on ledger/ledger_test.go
> +	genesisInitState, initSecrets := testGenerateInitState(t, protocol.ConsensusV15)
that's good observation; V7 is where Adam stopped with the consensus parameter folding.

2021-02-01 19:07 UTC, tsachiherman commented
@nicholasguoalgorand - I'm adding you so that you'll be aware of the changes in here. You don't have to approve this one, just go over and make sure you're familiar with the changes.

2021-02-01 19:52 UTC, tsachiherman commented
it looks like travis fails due to "make lint". Could you try to run this ?

2021-02-04 00:02 UTC, zeldovich commented
@tsachiherman , looks like I found all of the references to old protocols that happened to use the old Merkle-tree commitment for transactions.  (I did not realize our tests were still exercising that code!)  Feel free to merge whenever you're happy with it.

2021-02-04 01:30 UTC, tsachiherman approved these changes

2021-02-04 01:31 UTC, merged