Update systemd-setup.sh to install system.json
algorand/go-algorand pull request #2651
Opened 2021-07-28 18:24 UTC by bricerisingalgorand

## Summary

Right now a system.json file is not created when setting up systemd through the setup-systemd.sh script. Therefore, users aren't letting their nodes know that the algod process will be managed with systemd. This change has the setup-systemd.sh script download the systemd system.json file and lets the user know they need to copy that into any systemd managed data directory.

## Test Plan

I ran the script on a raspberry pi and saw that it worked.

2021-07-28 18:49 UTC, algobarb approved these changes
looks good

2021-07-28 20:16 UTC, onetechnical requested changes

2021-07-28 20:16 UTC, onetechnical commented on installer/algorand@.service.template
> +ExecStartPre=bash -c "[[ ! -f /home/pi/node/data/system.json ]] && echo '{\"shared_server\":true,\"systemd_managed\":true}' > /home/pi/node/data/system.json || :"
Hardcoded path

```suggestion
ExecStartPre=bash -c "[[ ! -f %I/system.json ]] && echo '{\"shared_server\":true,\"systemd_managed\":true}' > %I/system.json || :"
```

2021-07-28 20:56 UTC, winder commented on cmd/goal/messages.go
> +	errorNodeManagedBySystemd         = "This node is managed by systemd, you must run the following command to make your desired state change to your node:\n\nsystemctl %s algorand@$(systemd-escape $AL
nit: This command doesn't work for all shells. What do you think about redirecting them to the website instead?
```suggestion
	errorNodeManagedBySystemd         = "This node is using systemd and should be managed with systemctl. For additional information refer to https://developer.algorand.org/docs/run-a-node/setup/install/#installing-algod-as-a-systemd-service"
```

2021-07-28 21:08 UTC, onetechnical submitted a review, later dismissed
Tentative approval; Will's comment on pointing to docs is interesting, and Jack's suggestion to remove the system.json file on stopping is also intriguing, so would be open to either/both those improvements.

2021-07-28 21:16 UTC, algojack approved these changes

2021-07-29 02:05 UTC, egieseke approved these changes
Looks good.

2021-07-29 02:11 UTC, bricerisingalgorand commented
I think deleting the system.json might be a good idea, but it depends on the purpose we have in mind for it. If it’s meant to only reserve certain interactions with the node after every start that makes sense, but if it’s meant to always restrict the node in some instances it wouldn’t. We may want to consider that design decision more before we make it.

I think Will is right that we should refer to the docs instead of giving prescriptive feedback here though, so I just committed that change 👍

2021-07-29 14:09 UTC, onetechnical approved these changes
Looks good; did you run it / does it work?

2021-07-29 14:19 UTC, bricerisingalgorand commented
Yep, I made sure the file gets created, doesn't get edited when it exists and here are the goal messages

```
pi@raspberrypi:~ $ ./goal node stop
This node is using systemd and should be managed with systemctl. For additional information refer to https://developer.algorand.org/docs/run-a-node/setup/install/#installing-algod-as-a-systemd-service
pi@raspberrypi:~ $ ./goal node start
This node is using systemd and should be managed with systemctl. For additional information refer to https://developer.algorand.org/docs/run-a-node/setup/install/#installing-algod-as-a-systemd-service
pi@raspberrypi:~ $ ./goal node restart
This node is using systemd and should be managed with systemctl. For additional information refer to https://developer.algorand.org/docs/run-a-node/setup/install/#installing-algod-as-a-systemd-service
```

2021-07-29 14:26 UTC, algobarb approved these changes
Output that Brice posted looks good.

2021-07-29 14:28 UTC, egieseke approved these changes
Looks good, one comment about the message.

2021-07-29 14:28 UTC, egieseke commented on cmd/goal/messages.go
> +	errorNodeManagedBySystemd         = "This node is using systemd and should be managed with systemctl. For additional information refer to https://developer.algorand.org/docs/run-a-node/setup/install
Possibly add "Detected system.json file in the data directory, this node is using systemd and should be ..."

2021-07-29 14:30 UTC, merged

2021-08-03 12:37 UTC, tsachiherman commented
@bricerisingalgorand - I'm not a bit fan of providing exact documentation links inside the binary since the documentation links could change over time, forcing us to update the codebase for no good reason.
regardless of that, while changing the error string you forgot to change the corresponding expect test, which is testing against that string. ( admittedly, the expect tests are currently disabled, since they were causing random build failures )

2021-08-03 20:05 UTC, bricerisingalgorand commented
> @bricerisingalgorand - I'm not a bit fan of providing exact documentation links inside the binary since the documentation links could change over time, forcing us to update the codebase for no good reason.
> regardless of that, while changing the error string you forgot to change the corresponding expect test, which is testing against that string. ( admittedly, the expect tests are currently disabled, since they were causing random build failures )

Oh shoot, thanks I'll fix that. Also I can change the error message back to a suggested systemctl command if that's better