Feature/2644 faster pingpong
algorand/go-algorand pull request #2653
Opened 2021-07-28 19:45 UTC by AlgoStephenAkiki

Resolves #2644 

Removes signing calls to KMD by creating internal hashmap and signing transactions locally.

## Summary

## Test Plan

2021-07-28 19:56 UTC, brianolson commented
Still should have local storage for generated accounts

2021-07-28 20:23 UTC, tsachiherman commented on shared/pingpong/pingpong.go
> +	for addr, val := range accounts {
`val` -> `acct`

2021-07-28 20:27 UTC, tsachiherman commented on shared/pingpong/pingpong.go
> +type pingPongAccount struct {
add a very short line of comment explaining what this struct is used for.

2021-07-28 20:27 UTC, tsachiherman commented on shared/pingpong/pingpong.go
> +	//accounts map[string]uint64
drop commented out lines.

2021-07-28 23:22 UTC, tsachiherman commented on shared/pingpong/pingpong.go
> +		psig = accounts[signer].sk.Sign(logic.Program(cfg.Program))
I could be wrong, but I think that you might want to do
```golang
progb := logic.Program(cfg.Program)
psig = accounts[signer].sk.Sign(&progb)
```

2021-07-28 23:25 UTC, tsachiherman requested changes
This PR seems to fail for the following test cases:
asset_transfer_small, asset_transfer_large, stateful_teal_small, stateful_teal_medium, stateful_teal_large.
Could you manually test that locally and make sure it generates valid transactions ?

2021-07-31 01:23 UTC, tsachiherman approved these changes
looks good.

2021-07-31 01:23 UTC, merged