Shant/fix synch test
algorand/go-algorand pull request #2844
Opened 2021-09-05 19:47 UTC by algonautshant

## Summary

When multiple threads use the synchTest object, and one fails, all call FailNow.

After the first call, the main test routine reads t.finished to terminate the test.

While the main test routine is reading t.finished, another thread calls FailNow, which in turn writes to t.finished, causing the data race.

While FailNow called from synchTest are guarded by a mutex, the main testing object has the TestingTB object, which does not use the same mutex.

The solution is to call FailNow from synchTest object only the first time.

fixes #2507

### More details:
The problem with the string of data race conditions we are observing in different tests when the test fails is the following:

When the test fails, FailNow in go/src/testing/testing.go sets `c.finished`, which is the "Previous write" part of the data race
```
func (c *common) FailNow() {
...
	c.finished = true
...
```
this call comes from different threads, possibly multiple ones, forked from (not exclusively) 
go-algorand/nodecontrol/algodControl.go
```
func (nc *NodeController) StartAlgod(args AlgodStartArgs) (alreadyRunning bool, err error) {
...
	go func() {
...
			if args.ExitErrorCallback != nil {
				args.ExitErrorCallback(nc, err)
```
where, `ExitErrorCallback` is:
```
func (f *LibGoalFixture) nodeExitWithError(nc *nodecontrol.NodeController, err error) {
...
		require.NoError(f.t, err, "Node at %s has terminated with an error", nc.GetDataDir())
...
}
```
and NoError, in case of an error, calls `FailNow`.

`f.t` happens to be `synchTest`, which has a mutex guarding the `FailNow` call, and hence, prevents simultaneous access `t.finished`.

However, there is one more read access to `t.finished`, which comes from the following location, which does not use synchTest object, hence, does not have the mutex used for the write:

go/src/testing/testing.go
```
func tRunner(t *T, fn func(t *T)) {
...
	defer func() {
...
		if !t.finished && err == nil {
```

In other words, when there are multiple threads, and all are fine, no thread will write to `t.finished`. When something goes wrong and `FailNow` is initiated, the other threads will be notified of the failure, and, in their turn, also report `require.NoError`, which calls `FailNow`, and writes `t.finished = true`.

## Test Plan

2021-09-08 18:58 UTC, tsachiherman commented
Based on the details you've provided, I don't believe that the proposed solution would fix the issue:
Consider the case where a new AlgodController is being created, and it's getting returned with an error *after* the test ends (without reporting any issue ). It would still call the "t.Fail", which would datarace with the tRunner.
I think that we should disable all Fail calls once we've completed the test execution. We can do that using a destructor, in a similar way to `SetTestContext()`

2021-09-09 04:04 UTC, algonautshant commented
You are right. My changes addressed only failures caused by the test, but not failures coming from the fixture. 
This change should address it. I still need to update other tests with this.

2021-09-10 12:40 UTC, tsachiherman commented on test/framework/fixtures/fixture.go
> +// TerminateTestFailures should be called within each test using a shared fixture.
I'm not sure if that's true only for shared fixtures.

2021-09-10 12:51 UTC, tsachiherman commented on test/framework/fixtures/fixture.go
> +	if !st.dontReportFailures {
we'll need the same for Error/Errorf/Fatal/Fatalf/Skip***

2021-09-10 12:56 UTC, tsachiherman commented on test/framework/fixtures/fixture.go
> +func TerminateTestFailures(t TestingTB) {
maybe `ShutdownSynchronizedTest` ?

2021-09-10 19:44 UTC, tsachiherman requested changes
looks good. make sure to fix
```sh
Go files must be formatted with gofmt. Please run:
  gofmt -w /home/circleci/project/test/e2e-go/upgrades/application_support_test.go
```

2021-09-11 02:03 UTC, tsachiherman approved these changes
loos good.

2021-09-11 02:04 UTC, merged