Add ledger.GetBlockAddresses()
algorand/go-algorand pull request #2872
Opened 2021-09-11 04:32 UTC by tolikzinovyev

## Summary

Indexer needs to know all accounts referenced in a block to be able to read all of them in one batch. This PR creates a function that returns all such account addresses.

2021-09-11 19:05 UTC, tsachiherman requested changes
The change looks good - but they don't perform that great. I tested your changes using
```sh
go test -v . --run XX --bench BenchmarkBlockEvaluatorRAMNoCrypto -count=10 | grep BenchmarkBlockEvaluatorRAMNoCrypto
```

and received the following performance metrics on master:
```sh
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 945332700 ns/op	     18907 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 887004810 ns/op	     17741 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 898731697 ns/op	     17976 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 905146646 ns/op	     18104 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 895749462 ns/op	     17916 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 876699177 ns/op	     17535 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 889700168 ns/op	     17795 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 888446000 ns/op	     17770 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 888201852 ns/op	     17765 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 916630812 ns/op	     18333 ns/eval_validate_tx
```

compared to the ones from your branch:
```sh
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       1	1016715840 ns/op	     20335 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       1	1026562100 ns/op	     20533 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	1005568624 ns/op	     20112 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       1	1008136765 ns/op	     20164 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       1	1016944071 ns/op	     20340 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	1016153946 ns/op	     20324 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 974119522 ns/op	     19483 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 957210924 ns/op	     19145 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 879668276 ns/op	     17594 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 913933502 ns/op	     18279 ns/eval_validate_tx
```

In the vast of the cases, `master` perform better compared to your branch. I would suggest that you'll keep the existing implementation of `loadAccounts` as is, and just have your own changes ( you might want to add some comments that it's a code duplication that need to be converged ).

For the purposes of the indexer, we can optimize that code on another task - but there is no reason to introduce a regression to the master.

2021-09-13 15:11 UTC, winder commented
Would it make sense to add this as a function to SignedTxnInBlock instead of as part of the evaluator?

2021-09-13 15:16 UTC, tsachiherman commented
> Would it make sense to add this as a function to SignedTxnInBlock instead of as part of the evaluator?

I would be ok if we were to add the method to the `transactions` package. But why `SignedTxnInBlock` and not `Transaction` ?

2021-09-13 15:46 UTC, winder commented
> > Would it make sense to add this as a function to SignedTxnInBlock instead of as part of the evaluator?
> 
> I would be ok if we were to add the method to the `transactions` package. But why `SignedTxnInBlock` and not `Transaction` ?

`Transaction` would be better. I was thinking we needed the `ApplyData` in order to figure out who participates in the inner transactions, but `txn.ApplicationCallTxnFields.Accounts` is available for that.

Do we always need all of these accounts available?  I suppose the TEAL evaluation needs to read accounts regardless of whether they are modified...

If all of these accounts are added to the `txn participation` table, this is going to change the result of a txns by account lookup. We may want to add this to the release notes, and possibly add a new address role for it.

2021-09-13 16:48 UTC, tolikzinovyev commented
I can't reproduce the difference in performance (perhaps because I'm using the newest version of go). I changed the code slightly. Could you run the benchmark again?

2021-09-13 17:41 UTC, tsachiherman commented
> I can't reproduce the difference in performance (perhaps because I'm using the newest version of go). I changed the code slightly. Could you run the benchmark again?

I'm using 
```ssh
go version go1.16.7 darwin/amd64
```

and running the same benchmark again:
```ssh
BenchmarkBlockEvaluatorRAMNoCrypto
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 937884934 ns/op	     18758 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	1104762888 ns/op	     22097 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       1	1051855114 ns/op	     21039 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 945192180 ns/op	     18905 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 964409754 ns/op	     19289 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 896160418 ns/op	     17924 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 945274962 ns/op	     18906 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 971673884 ns/op	     19435 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       1	1020561048 ns/op	     20412 ns/eval_validate_tx
BenchmarkBlockEvaluatorRAMNoCrypto-8   	       2	 971733400 ns/op	     19436 ns/eval_validate_tx
```
is slightly better, but not there yet.

2021-09-13 17:57 UTC, tolikzinovyev commented
It might be something to do with the new optimization in go 1.17. https://golang.org/doc/go1.17#compiler

How significant is this benchmark anyway? The cost of eval should be dominated by crypto and disk.

2021-09-13 18:02 UTC, tsachiherman commented
There is no reason to have any performance loss for adding new, non-interfering functionality. I'm sure that the performance loss would have been much more noticeable if we had a benchmark for loadAccounts - but we don't.

Given that refactoring this code isn't really what you're after, just rollback the changes in `loadAccounts` and it will be good to go. Once we move to go 1.17, I'll be more than happy to re-test that.

2021-09-13 19:05 UTC, tsachiherman commented on ledger/eval.go
> +	*out = append(txn.ApplicationCallTxnFields.Accounts)
I think that you meant 
```golang
*out = append(*out, txn.ApplicationCallTxnFields.Accounts...)
```

2021-09-13 19:08 UTC, tolikzinovyev commented on ledger/eval.go
> +	*out = append(txn.ApplicationCallTxnFields.Accounts)
thanks!

2021-09-13 19:11 UTC, tsachiherman approved these changes
looks good to me.

2021-09-13 20:22 UTC, merged