Compress msgOrderingHeap
algorand/go-algorand pull request #3343
Opened 2021-12-21 20:48 UTC by nicholasguoalgorand

## Summary

Whenever the msgOrderingHeap gets full, we would like to compress the messages inside of it instead of disconnecting from the corresponding peer.

## Test Plan

Wrote additional unit tests.

2021-12-22 15:48 UTC, tsachiherman commented on txnsync/msgorderingheap.go
> +func (p *messageOrderingHeap) compress() {
maybe rename "compress" -> "compact" ? The "compress" keyword implies a reversible packing action, which isn't the case here.

2021-12-22 16:16 UTC, tsachiherman commented on txnsync/msgorderingheap.go
> +		}
instead of popping and pushing back, use `popSequence`.

2021-12-22 16:23 UTC, tsachiherman requested changes
I think that the changes here are a good start, but we would require more changes for this to work ( including some testing that shows that this works.. )

Specifically, in `incoming.go`, each message that being placed on the `incomingMessages` should contain it's "starting" seq number, as well as the "next message seq number". i.e. in `asyncIncomingMessageHandler`, you should initialize `incomingMessage.NextSequenceNumber` with `sequenceNumber+1`. When compacting the heap, you should retain the sequenceNumber for the first entry, and update the NextSequenceNumber for the last entry.
Last, you'll need to use that in `evaluateIncomingMessage`.

2022-01-05 16:11 UTC, nicholasguoalgorand commented
> ```go
> nextEntry.nextSequenceNumber = compressedEntry.nextSequenceNumber
> ```

Are you sure? This will keep the nextSequenceNumber of the oldest message.

2022-01-06 20:27 UTC, tsachiherman approved these changes

2022-01-06 20:27 UTC, merged