update branch from master
algorand/go-algorand pull request #3396
Opened 2022-01-07 19:49 UTC by tsachiherman

## Summary

Update branch from master

2022-01-07 21:37 UTC, cce submitted a review, later dismissed

2022-01-07 22:04 UTC, algorandskiy requested changes
Please skip tests instead of commenting them out

2022-01-07 22:10 UTC, tsachiherman commented on ledger/acctupdates_test.go
> +/*func TestAcctUpdatesLookupRetry(t *testing.T) {
there was a compilation error. I'll re-iterate on these after merging this one.
( I want to make sure the CI complete the code verification step )

2022-01-07 22:10 UTC, tsachiherman commented on ledger/catchpointtracker_test.go
> +/*func TestReproducibleCatchpointLabels(t *testing.T) {
same issue as above.

2022-01-07 22:12 UTC, tsachiherman commented on network/limitlistener/helper_stub_test.go
> +// Copyright 2014 The Go Authors. All rights reserved.
there is already an exclusion for that. "Go Authors".

2022-01-07 22:18 UTC, algorandskiy commented on ledger/catchpointtracker_test.go
> +/*func TestReproducibleCatchpointLabels(t *testing.T) {
```
git log -1 --pretty=oneline
53be86a729b5de9a462fc282602938079184a999 (HEAD -> pavel/ledger-perf-1, upstream/feature/unlimited-assets) ledger refactoring: catchpoint fixes (#3374)

go test ./ledger -run TestReproducibleCatchpointLabels -count=1
ok      github.com/algorand/go-algorand/ledger  3.389s
```
No compilation errors. If so than it should be a merge error

2022-01-10 15:59 UTC, algorandskiy commented on ledger/catchpointtracker_test.go
> +/*func TestReproducibleCatchpointLabels(t *testing.T) {
fixed, it was a merging error

2022-01-10 16:00 UTC, cce approved these changes

2022-01-10 16:35 UTC, merged