Add `SqliteReadConcurrency` parameter
algorand/go-algorand pull request #3399
Opened 2022-01-08 02:20 UTC by tolikzinovyev

## Summary

Add `SqliteReadConcurrency` parameter to local config and take it into account when calculating the number of available file descriptors required. `SqliteReadConcurrency` is then used to limit number of read "connections" to the block and tracker databases.

Each database "connection" will create 3 file descriptors for opening the database: .sqlite, sqlite-shm and .sqlite-wal. The current FD budgeting doesn't account for this.

## Test Plan

None.

2022-01-12 22:05 UTC, algorandskiy commented on daemon/algod/server.go
> +	}
why is in a block?

2022-01-12 22:05 UTC, algorandskiy commented on config/localTemplate.go
> +	SqliteReadConcurrency uint64 `version[20]:"128"`
where does 128 come from?

2022-01-14 17:36 UTC, tolikzinovyev commented on daemon/algod/server.go
> +	}
to hide `sqliteFds`

2022-01-14 17:41 UTC, tsachiherman requested changes
As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call.
I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.

2022-01-14 17:48 UTC, tolikzinovyev commented
> As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call. I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.

Can't REST endpoints slow down internal processing without this change? I don't really see the difference.
What kind of e2e test?

2022-01-14 17:54 UTC, tsachiherman commented
> > As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call. I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.
> 
> Can't REST endpoints slow down internal processing without this change? I don't really see the difference. What kind of e2e test?

Right now, the number of sqlite readers isn't limited. So in theory, it would slow down the internal performance only once it exceeded the underlying hardware capabilities. With your change, you're capping it at the driver level. That could lead to starvation of a node's internal operation, which I'd rather avoid.

2022-01-14 17:56 UTC, tsachiherman commented
> > As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call. I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.
> 
> Can't REST endpoints slow down internal processing without this change? I don't really see the difference. What kind of e2e test?

The e2e test that I'm thinking of would create a network, saturate it with some kind of load, and be able to cause the node to crash due to high number of concurrent database queries.

2022-01-14 18:00 UTC, tolikzinovyev commented
> > > As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call. I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.
> > 
> > 
> > Can't REST endpoints slow down internal processing without this change? I don't really see the difference. What kind of e2e test?
> 
> Right now, the number of sqlite readers isn't limited. So in theory, it would slow down the internal performance only once it exceeded the underlying hardware capabilities. With your change, you're capping it at the driver level. That could lead to starvation of a node's internal operation, which I'd rather avoid.

If it's only a matter of number 128, we can increase it. However, I don't think a bigger number would make a difference.

2022-01-14 18:02 UTC, tolikzinovyev commented
> > > As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call. I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.
> > 
> > 
> > Can't REST endpoints slow down internal processing without this change? I don't really see the difference. What kind of e2e test?
> 
> The e2e test that I'm thinking of would create a network, saturate it with some kind of load, and be able to cause the node to crash due to high number of concurrent database queries.

I wasn't able to cause a crash, probably because ssds are too fast or some sqlite caching was involved. In any case, the way I see it, with this change there is a proof that crash won't happen due to FD exhaustion, without this change I don't have such proof.

2022-01-14 18:03 UTC, tsachiherman commented
> > > > As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call. I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.
> > > 
> > > 
> > > Can't REST endpoints slow down internal processing without this change? I don't really see the difference. What kind of e2e test?
> > 
> > 
> > Right now, the number of sqlite readers isn't limited. So in theory, it would slow down the internal performance only once it exceeded the underlying hardware capabilities. With your change, you're capping it at the driver level. That could lead to starvation of a node's internal operation, which I'd rather avoid.
> 
> If it's only a matter of number 128, we can increase it. However, I don't think a bigger number would make a difference.

No, the 128 number is good. It's the fact the these 128 database operations would be pulled out of the same pool as the internal operations.

2022-01-14 18:05 UTC, tolikzinovyev commented
> > > > > As implemented, I think that it's not a great implementation. It could slow down the internal processing due to a REST endpoint call. I would suggest creating a separate connection that would be used by the REST endpoints interface. However, before going into such an endeavor, I'd like to see some e2e test that shows that this is truly a viable issue.
> > > > 
> > > > 
> > > > Can't REST endpoints slow down internal processing without this change? I don't really see the difference. What kind of e2e test?
> > > 
> > > 
> > > Right now, the number of sqlite readers isn't limited. So in theory, it would slow down the internal performance only once it exceeded the underlying hardware capabilities. With your change, you're capping it at the driver level. That could lead to starvation of a node's internal operation, which I'd rather avoid.
> > 
> > 
> > If it's only a matter of number 128, we can increase it. However, I don't think a bigger number would make a difference.
> 
> No, the 128 number is good. It's the fact the these 128 database operations would be pulled out of the same pool as the internal operations.

There is a similar pool in the operating system with similar contention characteristics. If there is no contention in algod's pool, there will be contention in OS's pool.

2022-10-27 21:30 UTC, closed without merging