avoid generating log error on EnsureValidatedBlock / EnsureBlock
algorand/go-algorand pull request #3424
Opened 2022-01-16 05:54 UTC by algonautshant

In EnsureBlock,, do not log as error message if the error is `ledgercore.ErrNonSequentialBlockEval` and the block round is in the past (i.e. already in the ledger). 

Added a test to verify the behavior. 

resolves #1831

2022-01-18 14:13 UTC, tsachiherman requested changes
Thinking about this over the weekend, I think it would be better to "convert" the `ledgercore.ErrNonSequentialBlockEval` to `ledgercore.BlockInLedgerError` in `ledger.AddBlock` when err != nil and EvaluatorRound <= errNSBE.LatestRound.

The handling for both cases is the same and it would simplify the client code.

2022-01-18 14:14 UTC, tsachiherman requested changes
in addition to the above, please also make sure to use distinguishable log messages, so that we could trace these back if/when needed.

2022-01-19 21:43 UTC, tsachiherman approved these changes
looks good.

2022-01-19 21:49 UTC, algorandskiy approved these changes

2022-01-20 00:18 UTC, merged