multi-label support
algorand/go-algorand pull request #3713
Opened 2022-03-03 20:55 UTC by tsachiherman

## Summary

## Test Plan

2022-03-03 21:13 UTC, cce commented on util/metrics/counter.go
> +			values[counter.name+"["+label+"]"] = strconv.FormatFloat(value.counter, 'f', -1, 32)
These names end up as JSON field keys in the heartbeat, and any string is a valid key, but I think this is as fine an encoding as any.

2022-03-03 21:17 UTC, cce commented
I modified @brianolson's benchmark from #1938 to use `Counter.Inc` with pre-created labels `map[string]string{"tag": "val"}` instead of `TagCounter.Add` and the difference was stark .. 19ns/op vs 5460 ns/op for using Counter.Inc

2022-03-03 21:19 UTC, cce commented
Passing Counter.Inc(nil) brought it down to 7.6 ns/op which is in line with the comment "Much faster if labels is nil or empty."

2022-03-04 17:40 UTC, cce approved these changes

2022-03-04 18:08 UTC, cce requested changes
I wonder if it makes more sense to convert the handful of remaining users of 1-D labels with this to use TagCounters instead?

2022-03-04 18:14 UTC, tsachiherman commented
> I wonder if it makes more sense to convert the handful of remaining users of 1-D labels with this to use TagCounters instead?

I would not mind if we do both.

2022-05-03 04:50 UTC, algorandskiy commented
@cce maybe take over it, amend with the suggestion and merge in?

2023-04-21 14:09 UTC, closed without merging