Agreement: Add warning when decoding proposal of an unsupported consensus version
algorand/go-algorand pull request #3730
Opened 2022-03-08 21:26 UTC by nicholasguoalgorand

## Summary

When the agreement receives a proposal from a consensus version it cannot yet support, the node disconnects from the sender and logs the fact that it was unable to decode the proposal without providing guidance on the consensus version issue. This PR adds a warning message to the log specifying that the agreement cannot handle the consensus version's proposals

## Test Plan

2022-03-09 21:26 UTC, tsachiherman commented on agreement/message.go
> +type DecodeProposalError struct {
`DecodeProposalError` -> `errProposalDecoding`

2022-03-09 21:32 UTC, tsachiherman requested changes
you approach would work correctly for future cases, but not for past cases, since the decoder is still going to fail.
I would suggest a slightly more conservative approach of limiting the change to the demux, and testing against the latest round supported by the ledger.

How do I limit the change to the demux if I need to extract the round number of the provided proposal? And second, when you say testing against the latest round supported by the ledger, do you mean just check if the specified round > max supported round?

2022-03-10 03:11 UTC, nicholasguoalgorand commented
> you approach would work correctly for future cases, but not for past cases, since the decoder is still going to fail. I would suggest a slightly more conservative approach of limiting the change to the demux, and testing against the latest round supported by the ledger.



> you approach would work correctly for future cases, but not for past cases, since the decoder is still going to fail. I would suggest a slightly more conservative approach of limiting the change to the demux, and testing against the latest round supported by the ledger.

How do I limit the change to the demux if I need to extract the round number of the provided proposal? And second, when you say testing against the latest round supported by the ledger, do you mean just check if the specified round > max supported round?

2022-03-11 17:58 UTC, tsachiherman commented on agreement/demux.go
> +							d.log.Warnf("received proposal with unsupported consensus version: %v", cv)
The logic here looks correct. Two small tweaks:
1. if you're writing this new log message, then the other log message is no longer needed.
2. could you change the log message to something like 
d.log.Warnf("received proposal message was ignored. The node binary doesn't support the next network consensus (%v) and would no longer be able to process agreement messages", cv)

2022-03-14 13:53 UTC, tsachiherman submitted a review, later dismissed
looks good to me. I'd rather having these two identical cases merged, but logically this looks correct.

2022-03-14 17:06 UTC, nicholasguoalgorand commented
> looks good to me. I'd rather having these two identical cases merged, but logically this looks correct.

Whats a better way of writing this? I thought about ```// check protocol version
					cv, err := d.ledger.ConsensusVersion(d.ledger.NextRound())
					if err == nil {
						if _, ok := config.Consensus[cv]; !ok {
							d.log.Warnf("received proposal message was ignored. The node binary doesn't support the next network consensus (%v) and would no longer be able to process agreement messages", cv)
                                                          net.Disconnect(raw.MessageHandle)
					                d.UpdateEventsQueue(eventQueueTokenizing[tag], 0)
					                continue
						}
					}
					net.Disconnect(raw.MessageHandle)
					d.UpdateEventsQueue(eventQueueTokenizing[tag], 0)
					continue```

2022-03-14 19:51 UTC, tsachiherman approved these changes

2022-03-14 20:58 UTC, merged