Change ConsensusParams.MaxBalLookback.
algorand/go-algorand pull request #3875
Opened 2022-04-11 20:46 UTC by tolikzinovyev

## Summary

We no longer need to store 320 rounds, but we don't want to remove the lookback completely because the L2 contracts project uses it. This PR changes the value and updates comments/tests.

## Test Plan

2022-04-11 21:47 UTC, algorandskiy requested changes
As discussed on morning, please introduce a new parameter, and preserve the `MaxBalLookback` value because we rely on it in some places like expiration for the online account tail.

2022-04-11 21:47 UTC, algorandskiy commented on config/consensus.go
> +	vFuture.MaxBalLookback = 16;
I think we should not change `MaxBalLookback` but instead set add a new parameter.
We still need the original `MaxBalLookback` value in online account tracker to calculate expiration. We still need it in the catchpoint tracker to implement PoC for two stage catchpointing with backward compatibility.

2022-04-11 21:47 UTC, algorandskiy commented on test/e2e-go/features/transactions/asset_test.go
> +	consensusParams.MaxBalLookback = 16
this is the formula `320 = 2 * consensusParams.SeedLookback * consensusParams.SeedRefreshInterval`, it appears in couple places and should not be changed.

2022-04-12 02:59 UTC, tolikzinovyev commented
> As discussed on morning, please introduce a new parameter, and preserve the `MaxBalLookback` value because we rely on it in some places like expiration for the online account tail.

Actually, I don't know why `MaxBalLookback` exists. If you look at its description, it doesn't define the protocol but an implementation detail. I left it so that it can later be renamed to something like `L2ContractsLookback`. Imo, the online account tracker should use `2 * SeedLookback * SeedRefreshInterval` like the agreement does.

2022-04-12 19:48 UTC, closed without merging