Enhancement: Fixes Scenario 1 of on-chain warning
algorand/go-algorand pull request #4030
Opened 2022-05-23 15:27 UTC by AlgoStephenAkiki

Resolves #2060

Puts in booleans to deduct account status from online account data and
uses that to upgrade log messages to info from warnings if necessary

## Summary

## Test Plan

2022-05-24 08:23 UTC, AlgoStephenAkiki commented on node/node.go
> +			}
This is just for scenario 1 where the account has been closed.  We agreed that we would simply upgrade the log message to info here to stop spam.  In scenario 2 & 3 we would have a different log message.

2022-05-24 17:26 UTC, winder submitted a review, later dismissed

2022-06-06 18:42 UTC, AlgoStephenAkiki commented
Updated PR to include all scenario warnings.

2022-06-17 16:44 UTC, cce commented
No tests, was there manual testing to identify the logging working for S1/S2/S3?

2022-06-28 17:17 UTC, AlgoStephenAkiki commented
@cce  Could you look at the updated PR?

2022-07-07 21:59 UTC, cce commented on node/node_test.go
> +func OfflineOnlineClosedBitStatusTest(t *testing.T) {
This method doesn't start with Test, so it is not run by go test

2022-07-07 22:01 UTC, cce commented on node/node.go
> +		if warningFlags&bitMismatchingVotingKey != 0 {
it seems like you have unified the logging cases between bitMismatchingVotingKey and bitMismatchingSelectionKey, so you could just change this to be `warningFlags&bitMismatchingVotingKey != 0 || warningFlags&bitMismatchingSelectionKey != 0`?

2022-07-07 22:06 UTC, cce requested changes
Need to rename test, would be nice to consolidate duplication

2022-07-15 14:22 UTC, winder approved these changes

2022-07-19 16:47 UTC, merged