updater: use more-recent installer package
algorand/go-algorand pull request #4734
Opened 2022-11-02 14:09 UTC by algolucky

## Summary

- this updates `UPDATER_MIN_VERSION` to use a more recent version of the install package. `3.12.0` is important b/c it's the release where we recently renewed the signing keys.

2022-11-02 14:50 UTC, algojack submitted a review, later dismissed

2022-11-03 14:51 UTC, algobarb approved these changes
Good change

2022-12-02 14:53 UTC, onetechnical commented on cmd/updater/update.sh
> +UPDATER_MIN_VERSION="3.12.0"
```suggestion
UPDATER_MIN_VERSION="3.12.2"
```

2022-12-02 14:54 UTC, onetechnical requested changes
I guess this is unblocked now?

2022-12-02 15:47 UTC, excalq submitted a review, later dismissed

2022-12-02 17:08 UTC, algobarb approved these changes

2022-12-02 20:43 UTC, onetechnical approved these changes

2022-12-02 20:44 UTC, merged