Adding github release notes template
algorand/go-algorand pull request #5044
Opened 2023-01-23 18:59 UTC by algojack

in case we need it in future.

2023-01-24 22:08 UTC, excalq requested changes
Even if not a rename, nuke that `.release.yml` file so there isn't both.

2023-01-25 16:50 UTC, algojack commented
> Even if not a rename, nuke that `.release.yml` file so there isn't both.

it's a rename, didn't see it since it was with a dot

2023-01-25 16:58 UTC, algobarb approved these changes

2023-01-25 17:05 UTC, excalq approved these changes

2023-01-25 19:42 UTC, merged