tests: disable TestInitialSync on CI
algorand/go-algorand pull request #5053
Opened 2023-01-24 23:16 UTC by algorandskiy

## Summary

TestInitialSync creates 10 full nodes that is too much for CI builder.

## Test Plan

This is a test

2023-01-24 23:30 UTC, Eric-Warehime approved these changes

2023-01-25 00:14 UTC, algorandskiy commented on node/node_test.go
> +		t.Skip("Test is too heavy for amd64 builder running in parallel with other packages")
try `make test` and observe LA 32+ with all cores busy and 8+ test processes

2023-01-25 00:17 UTC, algonautshant commented on node/node_test.go
> +		t.Skip("Test is too heavy for amd64 builder running in parallel with other packages")
Is far as I know, tests do not run with others when t.Parallel() is not called. 
That the the whole reason why we have multiple runs on CircleCi.

If we are running things in parallel, something has changed!

2023-01-25 00:19 UTC, algonautshant commented on node/node_test.go
> +	"strings"
Not the right spot but... 

```suggestion
	"runtime"
	"strings"
```

2023-01-25 00:21 UTC, algorandskiy commented on node/node_test.go
> +		t.Skip("Test is too heavy for amd64 builder running in parallel with other packages")
t.Parallel() takes effect only within a single package (test binary)

2023-01-25 00:27 UTC, algonautshant requested changes
Thanks for doing this. 

A couple of more tests will have the same faith:
TestSyncingFullNode
TestSimpleUpgrade

2023-01-25 02:01 UTC, algonautshant approved these changes

2023-01-25 02:05 UTC, algorandskiy commented on node/node_test.go
> +		t.Skip("Test is too heavy for amd64 builder running in parallel with other packages")
oh, I expected it calling make test. Then it is very weird it fails time to time

2023-01-25 15:22 UTC, merged