refactor: remove sql.Tx from Batch
algorand/go-algorand pull request #5080
Opened 2023-01-30 20:35 UTC by icorderi

## Summary

## Test Plan

2023-02-10 16:51 UTC, algorandskiy reviewed
I cannot find anything wrong with this PR although the fact many Create* functions now error and they did not before. This affects not only writing but reading as well so there is possibility for producing different results on upgraded and non-upgraded nodes. Need to re-examine this.

This PR also misses Create -> Make rename as discussed earlier, and two tests migration from ledger to catchpoints

2023-02-10 16:51 UTC, algorandskiy commented on ledger/acctdeltas_test.go
> +func checkAccounts(t *testing.T, tx store.TransactionScope, rnd basics.Round, accts map[basics.Address]basics.AccountData) {
we need to stick to a common name for `store.TransactionScope`, now it is either ts or tx

2023-02-10 16:51 UTC, algorandskiy commented on ledger/acctdeltas_test.go
> +		arw, err := tx.CreateAccountsReaderWriter()
Create -> Make or New as discussed before

2023-02-10 16:51 UTC, algorandskiy commented on ledger/acctdeltas_test.go
> +		_ = tx.AccountsInitTest(t, accts, protocol.ConsensusCurrentVersion)
idk but `AccountsInitTest` in `TransactionScope` looks a bit weird abstraction

2023-02-10 16:51 UTC, algorandskiy commented on ledger/acctdeltas_test.go
> -func BenchmarkWritingRandomBalancesDisk(b *testing.B) {
suggestion: this is was a basic benchmark showing sqlite performance. Maybe moving to store/sql_test.go or removing as a separate commit/PR

2023-02-10 16:51 UTC, algorandskiy commented on ledger/acctonline.go
> +func (ao *onlineAccounts) commitRound(ctx context.Context, ts store.TransactionScope, dcc *deferredCommitContext) (err error) {
same ts vs tx

2023-02-10 16:51 UTC, algorandskiy commented on ledger/catchpointwriter.go
> +		rows, err := cw.tx.CreateKVsIter(ctx)
why Create? New/Make prefixes are common in go for such methods

2023-02-10 16:51 UTC, algorandskiy commented on ledger/catchpointwriter_test.go
> +		if expectedTotalResources != uint64(totalResources) {
can't totalResources and expectedTotalResources be the same type?

2023-02-10 16:51 UTC, algorandskiy commented on ledger/catchpointwriter_test.go
> +		if expectedTotalResources != uint64(totalResources) {
same type please

2023-02-10 16:51 UTC, algorandskiy commented on ledger/store/accountsV2.go
> +func (r *accountsV2Reader) AccountsAllTest() (bals map[basics.Address]basics.AccountData, err error) {
nit: since this is part of an interface probably need a better name AccountsAllTest -> GetAllAccountsTesting or similar

2023-02-16 19:34 UTC, AlgoAxel approved these changes
Just took a once over, but as I am also working this branch, I am familiar with it and given the checks passing, am comfortable adding my approval. As I helped in development on this PR, if we'd like another reviewer that's fine, but lots of this work was done by Ignacio before I started adding.

2023-02-17 19:44 UTC, algorandskiy approved these changes

2023-02-17 19:53 UTC, algorandskiy requested changes

2023-02-17 19:53 UTC, algorandskiy commented on ledger/acctonline.go
> +				ar, err := tx.MakeAccountsReader()
this looks not right. MakeAccountsReader calls AccountsInitDbQueries that prepares all queries. but this commit method needs only two.
This refactoring removes all benefits from having prepared queries and actually makes things worse from performance standpoint zero prepare vs ten prepare on each call

2023-02-17 20:06 UTC, algorandskiy approved these changes

2023-02-17 20:07 UTC, merged

2023-02-17 20:07 UTC, algorandskiy commented on ledger/acctonline.go
> +				ar, err := tx.MakeAccountsReader()
Resolving this - there are two MakeAccountsReader implementations, one with all prepared and other with lazy. looks ok.