Refactor: Push test-only functionality of storage interfaces into test-interface.
algorand/go-algorand pull request #5175
Opened 2023-03-01 19:17 UTC by AlgoAxel

* Moves test-only interface definitions to a `testinterface.go` file
* Adds ".Testing()" to any interface with extra Testing functionality. The implementation will return itself as a test-interface. If the interface isn't satisfied, that will be caught as a compilation error (in your IDE), so no typeCasting at play here :)
* Restores the "TestAcctOnlineTopDBBehindMemRound" test. in doing so I added one new test function to abstract away the SQL in the test.
* Marked any test-only functions with a note that they implement the testing interface.

testing implementations still live in their original files, which I decided looked cleaner now that the `Testing()` function is able to enforce interface satisfaction -- if you need to add a test method, but don't supply an implementation, you'll get IDE warnings right away.

2023-03-01 19:25 UTC, icorderi requested changes

2023-03-01 19:25 UTC, icorderi commented on ledger/store/trackerdb/testinterface.go
> +// to use test-only functionality, cast your Interface to the test-version, eg:
this comment is outdated.

2023-03-01 19:25 UTC, icorderi commented on ledger/store/trackerdb/sqlitedriver/testing.go
> +func ModifyAcctBaseTest(tx *sql.Tx) error {
this can be private

2023-03-01 20:10 UTC, icorderi submitted a review, later dismissed

2023-03-01 22:12 UTC, algorandskiy reviewed
LGTM, please fix all linter issues

2023-03-02 19:58 UTC, algorandskiy approved these changes

2023-03-02 21:37 UTC, icorderi approved these changes

2023-03-02 21:51 UTC, merged