chore: use ++ instead of +=
algorand/go-algorand pull request #5597
Opened 2023-07-23 16:49 UTC by kehiy

## Summary
I used `++` instead of `=+` 
they do the same thing but the `++` is more readable and more properly

2023-07-23 16:50 UTC, kehiy commented
@winder @algoanne 
can you review please

2023-07-24 12:37 UTC, winder approved these changes

2023-07-24 13:30 UTC, tzaffi requested changes
Thanks @kehiy for your pull request.

Though in most contexts I agree that `++` is preferable to `+= 1` in this specific context _of a simulation_ I disagree. For the case of `generate.go` I don't see an obvious reason why we'd want to skip a generation and add a number different than 1. However, in the case of `generate_test.go` it's already the case that sometimes we add numbers greater than 1 to intra so it's definitely clearer to use `+= 1` here. Summarizing, since this is a simulation and the amount we're advancing by is not a-priori 1, I think we should continue using the same style as before and not adopt `++`.

2023-07-24 18:16 UTC, kehiy commented
@tzaffi yep, that makes sense.
I'm going to close this PR, thanks for reviewing.

2023-07-24 18:16 UTC, closed without merging