chore: Remove unused phonebook method
algorand/go-algorand pull request #5615
Opened 2023-07-27 15:32 UTC by Eric-Warehime

## Summary
We never actually call ExtendPeerList anywhere. When we refresh the SRV list periodically it just fully replaces the peer list.

## Test Plan

grep'ing ExtendPeerList shows nothing. Also existing tests should pass.

2023-07-27 16:01 UTC, algorandskiy commented
If I remember right, it does not replace but merges. Otherwise `phonebook.json` and `-p` would not work?

2023-07-27 16:13 UTC, Eric-Warehime commented
> If I remember right, it does not replace but merges. Otherwise `phonebook.json` and `-p` would not work?

All occurrences in the repo according to github search:
https://github.com/search?q=repo%3Aalgorand%2Fgo-algorand%20ExtendPeerList&type=code

SRV updates use this to replace peer list on refresh.
https://github.com/algorand/go-algorand/blob/master/network/wsNetwork.go#L1775-L1785C2

Replace peer list on ws network create--which is where the -p overrides get passed in.
https://github.com/algorand/go-algorand/blob/master/network/wsNetwork.go#L2452C12-L2452C27

2023-07-27 16:39 UTC, algorandskiy commented
This sounds like a buggy behavior for me. `-p` entries must survive and not being replaced.

2023-07-27 16:44 UTC, iansuvak commented
I agree that we probably want clear semantics on the `-p` and the method naming.This change itself is safe but as @algorandskiy said we want to make sure that DNS refresh never clobbers manual peers provided via `-p`. Might be outside of the scope of this cleanup PR though.

2023-07-27 16:47 UTC, algorandskiy commented
>Might be outside of the scope of this cleanup PR though.

We'll need Extend function for this...

2023-08-01 14:44 UTC, winder approved these changes
Seems fine.

2023-08-02 15:07 UTC, iansuvak commented on network/wsNetwork.go
> +		wn.phonebook.ExtendPeerList(relayAddrs, string(wn.NetworkID), PhoneBookEntryRelayRole)
That does sound ok to me. If a relay get's removed from SRV it's either bad or unreachable, if it's unreachable it isn't doing real harm and if it's bad it's still only one of 4 relays (unless we remove multiple at once)

2023-08-02 15:19 UTC, algorandskiy approved these changes

2023-08-02 15:23 UTC, algorandskiy commented on network/wsNetwork.go
> +		wn.phonebook.ExtendPeerList(relayAddrs, string(wn.NetworkID), PhoneBookEntryRelayRole)
yeah, not great, then maybe we need a new "seeded" entries concept that survive in `ReplacePeerList` ?

2023-08-02 16:01 UTC, iansuvak submitted a review, later dismissed

2023-08-04 19:38 UTC, winder approved these changes

2023-08-04 19:43 UTC, algorandskiy requested changes
Blocking this, looks like folks think it should use replace logic with preserving seeded entries.

2023-08-04 21:00 UTC, Eric-Warehime commented
> Blocking this, looks like folks think it should use replace logic with preserving seeded entries.

That sounds like it should be done in a separate PR, but if we can't merge this without it then I can add it here.

2023-08-04 23:48 UTC, algorandskiy commented
> That sounds like it should be done in a separate PR, but if we can't merge this without it then I can add it here.

If we merge as is then dead relays could appear be in phonebook, not end of the world but still. This PR is just 5 LoC and the new fix will touch the same code, so I suggest to fix it right here.

2023-08-07 21:07 UTC, algorandskiy approved these changes

2023-08-08 15:49 UTC, iansuvak approved these changes
LGTM -- I like the property based testing

2023-08-08 16:29 UTC, merged