config: Add MaxBlockHistoryLookback option
algorand/go-algorand pull request #5749
Opened 2023-09-21 15:24 UTC by ohill

## Summary

There is no way to request a node to store more blocks if it is not archival. This adds a MaxBlockHistoryLookback similar to MaxAcctLookback config option.

## Test Plan

No tests yet

2023-09-21 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/go-algorand?pullRequest=5749) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/go-algorand?pullRequest=5749) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/go-algorand?pullRequest=5749) it.</sub>

2023-09-21 16:04 UTC, winder requested changes

2023-09-21 16:04 UTC, winder commented on ledger/ledger.go
> +	if configuredMinToSave := r.SubSaturate(basics.Round(l.cfg.MaxBlockHistoryLookback)); configuredMinToSave < minToSave {
Condition looks to be backwards. Presumably this value already takes into account the `1321` and `MaxAcctLookback` settings, so we need to ensure it doesn't shrink.
```suggestion
	if configuredMinToSave := r.SubSaturate(basics.Round(l.cfg.MaxBlockHistoryLookback)); configuredMinToSave > minToSave {
```

2023-09-22 13:36 UTC, winder commented on ledger/ledger.go
> +	if configuredMinToSave := r.SubSaturate(basics.Round(l.cfg.MaxBlockHistoryLookback)); configuredMinToSave < minToSave {
I mistook the variable to be "min number of rounds to save" when it is actually "minimum round to save". Looks like this code is correct.

2023-09-22 14:12 UTC, jannotti submitted a review, later dismissed
Seems good to me.

Do we ever complain about non-sensical combinations of config?  If someone sets this to, say, 3000 but also has Archival set, they are probably confused.

2023-09-25 19:21 UTC, algorandskiy commented on config/localTemplate.go
> +	MaxBlockHistoryLookback uint64 `version[31]:"0"`
I think v31 not released yet so it is fine

2023-09-25 19:22 UTC, algorandskiy reviewed
the code LGTM but please add a unit test and perform a manual test.

2023-09-28 15:28 UTC, algorandskiy approved these changes
Thank you for the change!

2023-09-28 19:31 UTC, algorandskiy approved these changes

2023-09-28 20:06 UTC, winder approved these changes

2023-09-28 20:34 UTC, merged