Update README.md to be more concise
algorand/go-algorand pull request #6099
Opened 2024-08-10 08:02 UTC by Pcharlesme

## Summary

## Test Plan

2024-08-10 08:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/go-algorand?pullRequest=6099) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/go-algorand?pullRequest=6099) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/go-algorand?pullRequest=6099) it.</sub>

2024-09-05 18:35 UTC, gmalouf commented
Hi @Pcharlesme ,

Appreciate the work put in here. We will not be adding/accepting a logo at this time to be included in the project. if you want to strip that content out, we can probably get this PR to be mergeable.

2024-09-05 18:45 UTC, gmalouf commented
Also important to flesh out the PR description of notable changes made.

2024-09-05 19:08 UTC, algorandskiy requested changes
Agreed with Gary - that external logo is not goer. Textural changes looks OK tho.

2024-09-05 21:54 UTC, Pcharlesme commented
@algorandskiy @gmalouf Thanks for your feedback 
Modification has been made as requested 
Notable changes are 
Detailed Node Running Instructions , Test Section
Detailed Sections on Interfacing, Deployment, and Utilities:

2024-09-14 08:25 UTC, Pcharlesme commented on README.md
> +```
File Updated

2024-09-14 08:25 UTC, Pcharlesme commented on README.md
> +```
@cce

2024-09-18 19:15 UTC, gmalouf approved these changes

2024-09-19 13:58 UTC, gmalouf commented
@Pcharlesme try rebasing to get latest from master/get build passing. README itself is looking good

2024-10-22 19:28 UTC, merged