REST API: genesis endpoint schema definition
algorand/go-algorand pull request #6157
Opened 2024-10-28 13:55 UTC by PhearZero

## Summary

Adds Genesis definition for endpoint and fixes invalid "string" response.

## Test Plan

- Updated schema definition
- Generated clients with `make generate`
- Run `scripts/travis/build_test.sh` to ensure nothing has changed

2025-02-20 16:13 UTC, gmalouf commented
@PhearZero - if you want to contribute this, you will need to rebase/merge in from master and then regenerate your schema definitions again after the recent changes.

2025-03-08 19:48 UTC, algorandskiy commented
@PhearZero please remerge with master and run `make generate`

2025-03-10 14:21 UTC, PhearZero commented
Thanks! Have been traveling, will bring this up to date.

2025-04-16 13:48 UTC, PhearZero commented
Absolutely @gmalouf ! Tried to debug this a bit yesterday, I am running into an issue with the generate command:

```bash
make generate
./scripts/check_deps.sh
[./scripts/check_deps.sh] Required dependencies installed.
PATH=/home/zero/go/bin:$PATH go generate ./...
stringer: no value for constant noop
agreement/actions.go:29: running "stringer": exit status 1
local_defaults.go
2025/04/16 09:17:05 
The swagger spec at "./swagger.json" is valid against swagger specification 2.0
stringer: no value for constant NoOpOC
data/transactions/application.go:62: running "stringer": exit status 1
stringer: no value for constant Sender
data/transactions/logic/fields.go:26: running "stringer": exit status 1
stringer: no value for constant AccountHK
ledger/store/trackerdb/hashing.go:32: running "stringer": exit status 1
stringer: no value for constant RoundConcluded
logging/logspec/agreement.go:27: running "stringer": exit status 1
make: *** [Makefile:142: generate] Error 1

```

I ran `make clean` but was not able to resolve the issue. Any suggestions on a resolution? 

(Ubuntu 24.04  go1.23.3 linux/amd64)

2025-04-16 16:18 UTC, PhearZero commented
The error was unrelated and was a user error on my part, I was not targeting the appropriate `Makefile`. 

Thank you for reminding me of this item @gmalouf, should be updated.

2025-04-17 06:39 UTC, algorandskiy requested changes

2025-04-17 06:39 UTC, algorandskiy commented on daemon/algod/api/server/v2/test/genesis_types_test.go
> +package test
missing license header

2025-04-17 06:39 UTC, algorandskiy commented on daemon/algod/api/server/v2/test/genesis_types_test.go
> +func getJsonTag(field reflect.StructField) string {
getJsonTag  -> getJSONTag as linter suggests

2025-04-17 06:39 UTC, algorandskiy commented
@PhearZero it is almost there, please resolve the remaining minor items

2025-04-28 14:46 UTC, gmalouf commented
@PhearZero Check out the remaining codegen and reviewdog failing checks - minor, but important changes left to get this wrapped up!

2025-04-29 18:27 UTC, gmalouf commented
@PhearZero because you changed one of the files in the API package, have to re-run the codegen locally and push (check out the codegen verification failure).

2025-04-29 20:08 UTC, algorandskiy approved these changes

2025-04-30 01:46 UTC, gmalouf approved these changes

2025-04-30 01:46 UTC, merged